### ISSUE TITLE
Discontinue SidWiz 2.1?

### ISSUE THREAD

**Issue by The-Beesh-Spweesh** [Pigu-A/SidWiz#1]
RushJet1 currently has a newer version of SidWiz 2 (r13.1). The latest build of SidWiz 2 from RushJet1 will always be attached in the About section on his YouTube channel. SidWiz "2.1" is a branch of the earliest build RushJet1 had ever released.  Even though RushJet's original download link on his "Doubt" video no longer works, it's here in the Releases tab.

The current version includes:

- More than 9 voices of this branch, up to 128.
- More than 9 columns, up to 50.
- Supports video/audio merging with MKVMerge instead of ffmpeg.
- Supports a ton of other options, including; thickness, alt-sync, and grid on/off
- Supports saving and loading templates

**Comment by Pigu-A** [comment]
Updated to r13.1 in https://github.com/Pigu-A/SidWiz/commit/5eb925e44ec96227b577c5ceda7083153071e8d1
